version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: car_db
    ports:
      - "3306:3306"
    networks:
      - car-net
    volumes:
      - mysql-data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  flask-app:
    build: .
    container_name: flask-app
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    networks:
      - car-net

networks:
  car-net:

volumes:
  mysql-data:

